# Generated by Django 4.2 on 2026-04-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, help_text='User-friendly reference number', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_preference',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('both', 'Both Email & SMS')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='country_of_residence',
            field=models.CharField(default='Malaysia', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='course_of_study',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_graduation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='id_expiry_date',
            field=models.DateField(blank=True, help_text='ID/Passport expiration date', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='id_issuing_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance & Banking'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('hospitality', 'Hospitality & Tourism'), ('construction', 'Construction'), ('student', 'Student'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Whether applicant is currently a student'),
        ),
        migrations.AddField(
            model_name='application',
            name='last_reviewed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='pdpa_consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Preferred name for communication', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_payment_method',
            field=models.CharField(blank=True, help_text='Preferred payment method', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes'),
        ),
        migrations.AddField(
            model_name='application',
            name='secondary_beneficiary_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='secondary_beneficiary_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='state_province',
            field=models.CharField(blank=True, help_text='State/Province (required for some countries)', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='terms_accepted_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='total_annual_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='university_country',
            field=models.CharField(blank=True, help_text='Country where studying', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='university_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/device information'),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_expiry_date',
            field=models.DateField(blank=True, help_text='Visa/Work permit expiration date', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_type',
            field=models.CharField(blank=True, choices=[('tourist', 'Tourist Visa'), ('business', 'Business Visa'), ('work', 'Work Visa'), ('student', 'Student Visa'), ('family', 'Family Visa'), ('residence', 'Residence Permit'), ('mm2h', 'MM2H (Malaysia My Second Home)'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='work_environment',
            field=models.CharField(blank=True, choices=[('office', 'Office-based'), ('outdoor', 'Outdoor/Field Work'), ('construction', 'Construction Site'), ('driving', 'Driving/Transportation'), ('student', 'Student'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='coverage_addons',
            field=models.JSONField(blank=True, default=dict, help_text='JSON of selected add-ons with prices'),
        ),
        migrations.AlterField(
            model_name='application',
            name='data_retention_expiry',
            field=models.DateField(blank=True, help_text='Auto-delete date (7 years from submission)', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='employer_name',
            field=models.CharField(blank=True, help_text='Company, institution, or self-employed', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(help_text='Full name as per identification document', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_number',
            field=models.CharField(help_text='Identification number (encrypted)', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('residence_permit', 'Residence Permit'), ('work_permit', 'Work Permit'), ('student_pass', 'Student Pass'), ('employment_pass', 'Employment Pass'), ('national_id', 'National ID'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='ip_address',
            field=models.CharField(blank=True, help_text='IPv4 or IPv6 at submission', max_length=45),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(help_text='Country of citizenship', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='pdpa_consent',
            field=models.BooleanField(default=False, help_text='Explicit PDPA consent - MUST be false by default'),
        ),
        migrations.AlterField(
            model_name='application',
            name='plan',
            field=models.CharField(choices=[('plan_5', 'Plan 5 (RM360,000)'), ('plan_6', 'Plan 6 (RM600,000)'), ('plan_7', 'Plan 7 (RM900,000)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='submitted', max_length=20),
        ),
    ]
