# Generated by Django 4.2 on 2026-04-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_application_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_type',
            field=models.CharField(choices=[('worker', 'Foreign Worker'), ('student', 'Foreign Student'), ('other', 'Other')], default='other', help_text='Distinguish between worker, student, and other applicants', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_registration_number',
            field=models.CharField(blank=True, help_text='Company registration number or employer ID', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_sponsoring_study',
            field=models.CharField(blank=True, help_text='Employer name if study is employer-sponsored', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_sponsorship_approved',
            field=models.BooleanField(default=False, help_text='Whether employer has approved/sponsored the work visa'),
        ),
        migrations.AddField(
            model_name='application',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent Employment'), ('contract', 'Contract-Based'), ('freelance', 'Freelance/Self-Employed'), ('temporary', 'Temporary Assignment')], help_text='Permanent, contract, freelance, or temporary', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='financial_proof_submitted',
            field=models.BooleanField(default=False, help_text='Whether financial proof documents have been submitted'),
        ),
        migrations.AddField(
            model_name='application',
            name='financial_proof_type',
            field=models.CharField(blank=True, choices=[('bank_statement', 'Bank Statement'), ('scholarship_letter', 'Scholarship Award Letter'), ('sponsor_letter', 'Sponsor Letter from Employer'), ('parents_declaration', 'Parents Financial Declaration'), ('investment_proof', 'Investment/Asset Proof'), ('other', 'Other Documentation')], help_text='Type of financial proof provided', max_length=25),
        ),
        migrations.AddField(
            model_name='application',
            name='intended_duration_months',
            field=models.IntegerField(blank=True, help_text='Intended duration of stay in Malaysia (in months)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly gross salary in MYR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='on_campus_residential',
            field=models.BooleanField(default=False, help_text='Whether student will reside on campus'),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_photo_exif_date',
            field=models.DateField(blank=True, help_text='EXIF metadata date from photo (extracted on client)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_photo_upload_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when photo was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_photo_url',
            field=models.URLField(blank=True, help_text='Uploadcare CDN URL for passport photo', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='professional_license_number',
            field=models.CharField(blank=True, help_text='Professional license/certification number (if applicable)', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship_award_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual scholarship/funding amount in MYR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship_name',
            field=models.CharField(blank=True, help_text='Name of scholarship or funding program', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='semester_start_date',
            field=models.DateField(blank=True, help_text='Date when current semester/course starts', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='study_level',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD / Doctoral'), ('certificate', 'Professional Certificate'), ('other', 'Other')], help_text='Level of study: Diploma, Bachelor, Master, PhD, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='study_sponsor_type',
            field=models.CharField(blank=True, choices=[('self_sponsored', 'Self-Sponsored'), ('scholarship', 'Scholarship-Funded'), ('employer_sponsored', 'Employer-Sponsored Study'), ('government_grant', 'Government Grant'), ('other', 'Other Funding')], help_text="How is the student's education being funded?", max_length=25),
        ),
        migrations.AddField(
            model_name='application',
            name='work_permit_expiry_date',
            field=models.DateField(blank=True, help_text='Work permit expiration date', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='work_permit_status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid Work Permit'), ('pending', 'Pending Application'), ('eligible', 'Eligible but Not Applied'), ('expired', 'Expired (Renewal Pending)'), ('other', 'Other Status')], help_text='Current work permit status in Malaysia', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='worker_category',
            field=models.CharField(blank=True, choices=[('category_1', 'Category 1: High-Skilled Professional (Specialist/Expert)'), ('category_2', 'Category 2: Skilled Worker (Technician/Supervisor)'), ('category_3', 'Category 3: General Worker (Administrative/Support)')], help_text='Malaysia labor regulation: 3 categories of foreign workers', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of work experience in current field', null=True),
        ),
    ]
