# Generated by Django 4.2 on 2026-04-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_applicant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('viewed', 'Viewed'), ('photo_uploaded', 'Photo Uploaded'), ('pdf_exported', 'PDF Exported')], max_length=20),
        ),
    ]
